BUENAFE, Lorenz Angelo N. <br>
1915058 <br>
CPE 019 - CPE32S9 <br>

Choose any dataset applicable to the classification problem, and also, choose any dataset applicable to the regression problem.

Classification - https://www.kaggle.com/datasets/bharath011/heart-disease-classification-dataset <br>

Regression - https://www.kaggle.com/datasets/anubhavgoyal10/laptop-prices-dataset


Explain your datasets and the problem being addressed.

https://www.kaggle.com/datasets/bharath011/heart-disease-classification-dataset <br>
The main purpose here is to collect characteristics of Heart Attack or factors that contribute to it. <br>

https://www.kaggle.com/datasets/anubhavgoyal10/laptop-prices-dataset <br>
This dataset can be used for regression analysis to predict the prices of laptops based on their features.

For classification, do the following: <br>
Create a base model <br>
Evaluate the model with k-fold cross validation <br>
Improve the accuracy of your model by applying additional hidden layers


1. Creating a base model

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import cross_val_score

In [2]:
df = pd.read_csv('/content/drive/MyDrive/CPE 019 Emerging Technologies 3/Assignment 7.1/Heart Attack.csv')


In [3]:
print(df.head)

<bound method NDFrame.head of       age  gender  impluse  pressurehight  pressurelow  glucose    kcm  \
0      64       1       66            160           83    160.0   1.80   
1      21       1       94             98           46    296.0   6.75   
2      55       1       64            160           77    270.0   1.99   
3      64       1       70            120           55    270.0  13.87   
4      55       1       64            112           65    300.0   1.08   
...   ...     ...      ...            ...          ...      ...    ...   
1314   44       1       94            122           67    204.0   1.63   
1315   66       1       84            125           55    149.0   1.33   
1316   45       1       85            168          104     96.0   1.24   
1317   54       1       58            117           68    443.0   5.80   
1318   51       1       94            157           79    134.0  50.89   

      troponin     class  
0        0.012  negative  
1        1.060  positive  


In [4]:
X = df.iloc[:, 0:4].values
y = df.iloc[:, 4].values

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
# Feature scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
mlp_classifier = MLPClassifier(hidden_layer_sizes=(50,), activation='relu', alpha=0.0001, batch_size=256, learning_rate_init=0.001, max_iter=500)
mlp_classifier.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(batch_size=256, hidden_layer_sizes=(50,), max_iter=500)

2. Evaluate the model with k-fold cross validation:

In [8]:
k_fold = 10
accuracies = cross_val_score(estimator=mlp_classifier, X=X_train, y=y_train, cv=k_fold)

print(f"Accuracy: {accuracies.mean()*100:.2f}% ({accuracies.std()*100:.2f}%)")

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochas

Accuracy: 7.67% (2.28%)


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


3. Improve the accuracy of your model by applying additional hidden layers:

In [9]:
mlp_classifier = MLPClassifier(hidden_layer_sizes=(50, 50, 50), activation='relu', alpha=0.0001, batch_size=256, learning_rate_init=0.001, max_iter=500)
mlp_classifier.fit(X_train, y_train)

# Evaluate the model on the test set
y_pred = mlp_classifier.predict(X_test)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("\nAccuracy Score:")
print(accuracy_score(y_test, y_pred))

Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]

Classification Report:
              precision    recall  f1-score   support

          38       0.00      0.00      0.00         0
          41       0.00      0.00      0.00         0
          42       1.00      1.00      1.00         1
          44       0.00      0.00      0.00         0
          45       0.00      0.00      0.00         1
          48       0.25      0.25      0.25         4
          49       0.00      0.00      0.00         2
          50       0.00      0.00      0.00         2
          51       0.00      0.00      0.00         3
          52       0.00      0.00      0.00         4
          53       0.00      0.00      0.00         3
          54       0.00      0.00      0.00         4
          55       0.00      0.00      0.00         7
          56       0.00      0.00      0.00         3
          57       0.25    

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being se

For regression, do the following: <br>
Create a base model <br>
Improve the model by standardizing the dataset <br>
Show tuning of layers and neurons (see evaluating small and larger networks)

1. Creating a base model

In [10]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [11]:
df = pd.read_csv('/content/drive/MyDrive/CPE 019 Emerging Technologies 3/Assignment 7.1/laptopPrice.csv')

In [12]:
# Remove unnecessary columns
df = df.drop(['rating', 'Number of Ratings', 'Number of Reviews'], axis=1)

# Convert categorical variables to numerical using one-hot encoding
df = pd.get_dummies(df)

# Split the dataset into features and target variable
X = df.drop('Price', axis=1)
y = df['Price']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [13]:
# Define the base model
model = Sequential()
model.add(Dense(64, activation='relu', input_dim=X_train.shape[1]))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='linear'))

# Compile the model
model.compile(loss='mean_squared_error', optimizer='adam')

# Train the model
model.fit(X_train, y_train, epochs=50, batch_size=32, verbose=1)

Epoch 1/50
21/21 [==============================] - 1s 2ms/step - loss: 7909235200.0000
Epoch 2/50
21/21 [==============================] - 0s 2ms/step - loss: 7908779520.0000
Epoch 3/50
21/21 [==============================] - 0s 2ms/step - loss: 7907524608.0000
Epoch 4/50
21/21 [==============================] - 0s 2ms/step - loss: 7904487936.0000
Epoch 5/50
21/21 [==============================] - 0s 2ms/step - loss: 7898453504.0000
Epoch 6/50
21/21 [==============================] - 0s 3ms/step - loss: 7888128000.0000
Epoch 7/50
21/21 [==============================] - 0s 3ms/step - loss: 7872027136.0000
Epoch 8/50
21/21 [==============================] - 0s 3ms/step - loss: 7849320448.0000
Epoch 9/50
21/21 [==============================] - 0s 3ms/step - loss: 7818050560.0000
Epoch 10/50
21/21 [==============================] - 0s 3ms/step - loss: 7778030592.0000
Epoch 11/50
21/21 [==============================] - 0s 3ms/step - loss: 7727673856.0000
Epoch 12/50
21/21 [===========

In [14]:
# Standardize the dataset
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Create a new model
model_scaled = Sequential()
model_scaled.add(Dense(64, activation='relu', input_dim=X_train_scaled.shape[1]))
model_scaled.add(Dense(32, activation='relu'))
model_scaled.add(Dense(1, activation='linear'))

# Compile and train the model
model_scaled.compile(loss='mean_squared_error', optimizer='adam')
model_scaled.fit(X_train_scaled, y_train, epochs=50, batch_size=32, verbose=1)

Epoch 1/50
21/21 [==============================] - 1s 2ms/step - loss: 7909236736.0000
Epoch 2/50
21/21 [==============================] - 0s 2ms/step - loss: 7908844032.0000
Epoch 3/50
21/21 [==============================] - 0s 2ms/step - loss: 7908256768.0000
Epoch 4/50
21/21 [==============================] - 0s 2ms/step - loss: 7907201024.0000
Epoch 5/50
21/21 [==============================] - 0s 2ms/step - loss: 7905420288.0000
Epoch 6/50
21/21 [==============================] - 0s 2ms/step - loss: 7902669312.0000
Epoch 7/50
21/21 [==============================] - 0s 2ms/step - loss: 7898300928.0000
Epoch 8/50
21/21 [==============================] - 0s 2ms/step - loss: 7892186112.0000
Epoch 9/50
21/21 [==============================] - 0s 2ms/step - loss: 7883592192.0000
Epoch 10/50
21/21 [==============================] - 0s 2ms/step - loss: 7872281600.0000
Epoch 11/50
21/21 [==============================] - 0s 2ms/step - loss: 7857424384.0000
Epoch 12/50
21/21 [===========

In [15]:
# Define a function to create a model with variable number of layers and neurons
def create_model(layers, neurons):
    model = Sequential()
    model.add(Dense(neurons[0], activation='relu', input_dim=X_train_scaled.shape[1]))

    for i in range(1, layers):
        model.add(Dense(neurons[i], activation='relu'))

    model.add(Dense(1, activation='linear'))

    model.compile(loss='mean_squared_error', optimizer='adam')
    return model

# Define the parameters for tuning
layers = [1, 2, 3]  # Number of hidden layers
neurons = [32, 64, 128]  # Number of neurons in each layer

# Perform grid search to find the best model
best_model = None
best_loss = float('inf')

for layer in layers:
    for neuron in neurons:
        model_tuned = create_model(layer, [neuron] * layer)
        model_tuned.fit(X_train_scaled, y_train, epochs=50, batch_size=32, verbose=0)
        loss = model_tuned.evaluate(X_test_scaled, y_test)

        if loss < best_loss:
            best_loss = loss
            best_model = model_tuned

# Print the best model's architecture and loss
print("Best model architecture:")
best_model.summary()
print("Best model loss:", best_loss)

6/6 [==============================] - 0s 3ms/step - loss: 695052544.0000
Best model architecture:
Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_29 (Dense)            (None, 128)               9344      
                                                                 
 dense_30 (Dense)            (None, 128)               16512     
                                                                 
 dense_31 (Dense)            (None, 128)               16512     
                                                                 
 dense_32 (Dense)            (None, 1)                 129       
                                                                 
Total params: 42497 (166.00 KB)
Trainable params: 42497 (166.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Best model loss: 695052544.0
